# Utilisez une image Python légère comme base
FROM python:3.9-slim

# Définissez le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez les fichiers nécessaires dans le conteneur
COPY requirements.txt requirements.txt

# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Copiez le reste du code dans le conteneur
COPY . .

# Exposez le port sur lequel le microservice s'exécutera
EXPOSE 5002

# Commande pour exécuter l'application
CMD ["python", "app.py"]
